language: node_js
node_js: node
cashe:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: uG/ffTU3WRwjINi36R6wpJCO8dfq8ECCJq4V7hz2ya8PW6thkNx3RP+UwWa0uSMSXpDxLz2Y8qUQhgGvsW8VbwjTs9wXDb9ZBw2zZb7HxwWdMN/7xvFy1qFTwsHzkejRXoDVplBxFGxB86uoFgxtW1tDKCgf3jLUr6/uwcbM9j044m5o3ghCyi601kzO11UTafUuvfHpigd58eCweYLjVnxlr715o81f/OUggkQ2u+R4pIB5QWHZ6H2hmgoEAPKwdhh3rYk1/6aU+Y7CBv63KQ4+idPSwT06ZQpk4RLToBbliAoENUAmhx6MPIE3IZLnumqeI1K23KuJU9GxF21meUmc0VKGXvsLuL5vaZyDXR1Bh0BZ3ypoDqCmCaag4UGnSnhJM51yF0Vaw1vDahOMdVAIX2wfEkdVu6Fr2uDU6x+Vzq5vVdWhkq3z7rJQBEw2gVhW4kfSJ2tFELA9sD9N9nMFmFQ6yU/f4/OGb0SgWFDfE7bHVXnYRGLqg2eFBLLTukViBi9rowXcD+lV+UEKr6u11LctyX4trDU7yaPmF0JU6mrmetNUPDwr0ImwuGsGtfDLMhsMXiCOg9bie0WYjq+Juc89YgoW5WoRs5DHd6wnrVzl4hFZDNEA7cLP/2ul2bnsSYJeenqQ1VPTXszwze8mF9hrqlMeoRJj6gU6KCc=
  app: pacific-basin-65264
  on:
    repo: amyspeed/IPA-Front-End
